CREATE TABLE `onboarding_submissions` (
	`id` int AUTO_INCREMENT NOT NULL,
	`dealership_name` varchar(255),
	`contact_email` varchar(320),
	`contact_phone` varchar(50),
	`crm_name` text,
	`crm_not_applicable` int NOT NULL DEFAULT 0,
	`dms_name` text,
	`dms_not_applicable` int NOT NULL DEFAULT 0,
	`website_provider` text,
	`website_not_applicable` int NOT NULL DEFAULT 0,
	`third_party_vendors` text,
	`third_party_not_applicable` int NOT NULL DEFAULT 0,
	`facebook_ads_usage` text,
	`facebook_ads_not_applicable` int NOT NULL DEFAULT 0,
	`marketplace_platforms` text,
	`marketplace_not_applicable` int NOT NULL DEFAULT 0,
	`backend_products` text,
	`backend_not_applicable` int NOT NULL DEFAULT 0,
	`subprime_lenders` text,
	`subprime_not_applicable` int NOT NULL DEFAULT 0,
	`sales_process_structure` text,
	`sales_process_not_applicable` int NOT NULL DEFAULT 0,
	`rehashing_lenders` text,
	`rehashing_not_applicable` int NOT NULL DEFAULT 0,
	`submitted_at` timestamp NOT NULL DEFAULT (now()),
	`status` enum('new','in_progress','completed') NOT NULL DEFAULT 'new',
	`notes` text,
	CONSTRAINT `onboarding_submissions_id` PRIMARY KEY(`id`)
);
